name: lighthouse-ci
on: workflow_dispatch

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set current date as env variable
        env:
          TZ: 'Asia/Tokyo' 
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set lighthouse ci env variables
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: $(node -e "new Date().getTime().toString(16).split('').reverse().join('')")
          LHCI_BUILD_CONTEXT__COMMIT_TIME: $(date --iso-8601=seconds)
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: master
          LHCI_BUILD_CONTEXT__COMMIT_MESSAGE: ${{ env.CURRENT_DATE }}
          LHCI_BUILD_CONTEXT__AUTHOR: "m0nch1 <m0nch1@st.inc>"
          LHCI_BUILD_CONTEXT__AVATAR_URL: "https://avatars.githubusercontent.com/u/5035741?s=200&v=4"
        run: echo ${{ env.LHCI_BUILD_CONTEXT__COMMIT_MESSAGE }}

      - name: run Lighthouse
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun